fix dnsdump function in striker.py dnsdump function allways raise exception: There was an error getting results
[+] DNS Records
Traceback (most recent call last):
File "striker.py", line 243, in
dnsdump(domain)
File "striker.py", line 175, in dnsdump
for entry in res['dns_records']['dns']:
TypeError: list indices must be integers, not str

This is because if we input 'http://www.xxx.com',the param domain of dnsdump(domain) will be 'www.xxx.com'.
The website 'https://dnsdumpster.com/' try to get 'www.xxx.com' 's subdomain, like 'aaa.www.xxx.com'. This is not the result we expected.
So we should set domain 'xxx.com', but not 'www.xxx.com'.